### ISSUE TITLE
How to remove/add animation?

### ISSUE THREAD

**Issue by BoltzmannBrain** [wemake-services/jekyll-theme-hackcss#12]
How can we remove the GitHub animation in the top-right corner?

Also wondering, in this framework, how to add animations? For example, [this typewriter effect](https://css-tricks.com/snippets/css/typewriter-effect/). Thanks in advance!

**Comment by sobolevn** [comment]
Hi! This is not actually a css or js framework. This is a template for new projects.

You can modify it as you with. Use all new plugins / css / js frameworks you need.

There's no special tooling / knowledge involved here.
I hope it helps. So, feel free to ask any other questions you have.
